[build.processing]
skip_processing = false  # Включаем обработку

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
minify = true

[build.processing.images]
compress = true
